# Fetching the latest node image on alpine linux
FROM node:alpine AS development

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /web

# Copy package.json and lock file
COPY package*.json ./

# Install all the dependencies
RUN npm install

# Copying all the files in our project
COPY . .

# Expose the development server port
EXPOSE 5173

# Start the development server
CMD ["npm", "run", "dev"]
