version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ${VITE_REACT_APP_DOCKERFILE}
    ports:
      - ${VITE_REACT_APP_PORT_MAP}
    volumes:
      - .:/web
      - /web/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_REACT_APP_GOOGLE_CLIENT_ID=${VITE_REACT_APP_GOOGLE_CLIENT_ID}
      - VITE_REACT_APP_GOOGLE_CLIENT_SECRET=${VITE_REACT_APP_GOOGLE_CLIENT_SECRET}
      - VITE_REACT_APP_SERVER_BASE_URL=${VITE_REACT_APP_SERVER_BASE_URL}
      - VITE_REACT_APP_CLIENT_BASE_URL=${VITE_REACT_APP_CLIENT_BASE_URL}
