version: "3.8"

services:
  react-app:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/react-app
      - /react-app/node_modules
    environment:
      NODE_ENV: development
      VITE_REACT_APP_GOOGLE_CLIENT_ID: 1026550055658-skeaoo2ipej0ntv2i5vtj3s7isgdhqg4.apps.googleusercontent.com
      VITE_REACT_APP_SERVER_BASE_URL: http://localhost:3000
      VITE_REACT_APP_CLIENT_BASE_URL: http://localhost:5173
